package com.google.android.gms.games.internal.player;

import android.os.Parcel;
import android.os.Parcelable.Creator;
import com.google.android.gms.common.internal.Objects;
import com.google.android.gms.common.internal.safeparcel.SafeParcelWriter;
import com.google.android.gms.games.internal.zzc;

public final class zze extends zzc {
    public static final Parcelable.Creator CREATOR;
    private final boolean zza;
    private final boolean zzb;
    private final boolean zzc;
    private final boolean zzd;
    private final boolean zze;
    private final boolean zzf;
    private final boolean zzg;
    private final boolean zzh;
    private final boolean zzi;

    static {
        zze.CREATOR = new zzf();
    }

    public zze(boolean z, boolean z1, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8) {
        this.zza = z;
        this.zzb = z1;
        this.zzc = z2;
        this.zzd = z3;
        this.zze = z4;
        this.zzf = z5;
        this.zzg = z6;
        this.zzh = z7;
        this.zzi = z8;
    }

    @Override
    public final boolean equals(Object object0) {
        if(!(object0 instanceof zze)) {
            return false;
        }
        return this == object0 ? true : this.zza == ((zze)object0).zza && this.zzb == ((zze)object0).zzb && this.zzc == ((zze)object0).zzc && this.zzd == ((zze)object0).zzd && this.zze == ((zze)object0).zze && this.zzf == ((zze)object0).zzf && this.zzg == ((zze)object0).zzg && this.zzh == ((zze)object0).zzh && this.zzi == ((zze)object0).zzi;
    }

    @Override
    public final int hashCode() {
        return Objects.hashCode(new Object[]{Boolean.valueOf(this.zza), Boolean.valueOf(this.zzb), Boolean.valueOf(this.zzc), Boolean.valueOf(this.zzd), Boolean.valueOf(this.zze), Boolean.valueOf(this.zzf), Boolean.valueOf(this.zzg), Boolean.valueOf(this.zzh), Boolean.valueOf(this.zzi)});
    }

    @Override
    public final String toString() {
        return Objects.toStringHelper(this).add("forbiddenToHavePlayerProfile", Boolean.valueOf(this.zza)).add("requiresParentPermissionToShareData", Boolean.valueOf(this.zzb)).add("hasSettingsControlledByParent", Boolean.valueOf(this.zzc)).add("requiresParentPermissionToUsePlayTogether", Boolean.valueOf(this.zzd)).add("canUseOnlyAutoGeneratedGamerTag", Boolean.valueOf(this.zze)).add("forbiddenToRecordVideo", Boolean.valueOf(this.zzf)).add("shouldSeeEquallyWeightedButtonsInConsents", Boolean.valueOf(this.zzg)).add("requiresParentConsentToUseAutoSignIn", Boolean.valueOf(this.zzh)).add("shouldSeeSimplifiedConsentMessages", Boolean.valueOf(this.zzi)).toString();
    }

    @Override  // android.os.Parcelable
    public final void writeToParcel(Parcel parcel0, int v) {
        int v1 = SafeParcelWriter.beginObjectHeader(parcel0);
        SafeParcelWriter.writeBoolean(parcel0, 1, this.zza);
        SafeParcelWriter.writeBoolean(parcel0, 2, this.zzb);
        SafeParcelWriter.writeBoolean(parcel0, 3, this.zzc);
        SafeParcelWriter.writeBoolean(parcel0, 4, this.zzd);
        SafeParcelWriter.writeBoolean(parcel0, 5, this.zze);
        SafeParcelWriter.writeBoolean(parcel0, 6, this.zzf);
        SafeParcelWriter.writeBoolean(parcel0, 7, this.zzg);
        SafeParcelWriter.writeBoolean(parcel0, 8, this.zzh);
        SafeParcelWriter.writeBoolean(parcel0, 9, this.zzi);
        SafeParcelWriter.finishObjectHeader(parcel0, v1);
    }
}

