package com.google.android.gms.internal.drive;

import com.google.android.gms.drive.metadata.MetadataField;
import com.google.android.gms.drive.metadata.internal.zzi;
import com.google.android.gms.drive.metadata.internal.zzo;
import com.google.android.gms.drive.metadata.internal.zzs;
import com.google.android.gms.drive.metadata.internal.zzt;
import com.google.android.gms.drive.metadata.internal.zzu;
import com.google.android.gms.drive.metadata.zzb;
import java.util.Collections;

public final class zzhs {
    public static final MetadataField zzjl;
    public static final MetadataField zzjm;
    public static final zzhv zzjn;
    public static final MetadataField zzjo;
    public static final MetadataField zzjp;
    public static final MetadataField zzjq;
    public static final MetadataField zzjr;
    public static final MetadataField zzjs;
    public static final MetadataField zzjt;
    public static final MetadataField zzju;
    public static final MetadataField zzjv;
    public static final MetadataField zzjw;
    public static final MetadataField zzjx;
    public static final MetadataField zzjy;
    public static final MetadataField zzjz;
    public static final zzhw zzka;
    public static final MetadataField zzkb;
    public static final MetadataField zzkc;
    public static final MetadataField zzkd;
    public static final MetadataField zzke;
    public static final MetadataField zzkf;
    public static final MetadataField zzkg;
    public static final MetadataField zzkh;
    public static final zzhx zzki;
    public static final MetadataField zzkj;
    public static final zzb zzkk;
    public static final zzu zzkl;
    public static final zzu zzkm;
    public static final zzo zzkn;
    public static final zzhy zzko;
    public static final zzia zzkp;
    public static final MetadataField zzkq;
    public static final zzib zzkr;
    public static final zzic zzks;
    public static final MetadataField zzkt;
    public static final MetadataField zzku;
    public static final MetadataField zzkv;
    public static final com.google.android.gms.drive.metadata.internal.zzb zzkw;
    public static final MetadataField zzkx;
    public static final MetadataField zzky;
    public static final zzhz zzkz;
    public static final MetadataField zzla;
    public static final MetadataField zzlb;

    static {
        zzhs.zzjl = zzim.zzlj;
        zzhs.zzjm = new zzt("alternateLink", 4300000);
        zzhs.zzjn = new zzhv(5000000);
        zzhs.zzjo = new zzt("description", 4300000);
        zzhs.zzjp = new zzt("embedLink", 4300000);
        zzhs.zzjq = new zzt("fileExtension", 4300000);
        zzhs.zzjr = new zzi("fileSize", 4300000);
        zzhs.zzjs = new zzt("folderColorRgb", 7500000);
        zzhs.zzjt = new com.google.android.gms.drive.metadata.internal.zzb("hasThumbnail", 4300000);
        zzhs.zzju = new zzt("indexableText", 4300000);
        zzhs.zzjv = new com.google.android.gms.drive.metadata.internal.zzb("isAppData", 4300000);
        zzhs.zzjw = new com.google.android.gms.drive.metadata.internal.zzb("isCopyable", 4300000);
        zzhs.zzjx = new com.google.android.gms.drive.metadata.internal.zzb("isEditable", 4100000);
        zzhs.zzjy = new zzht("isExplicitlyTrashed", Collections.singleton("trashed"), Collections.emptySet(), 7000000);
        zzhs.zzjz = new com.google.android.gms.drive.metadata.internal.zzb("isLocalContentUpToDate", 7800000);
        zzhs.zzka = new zzhw("isPinned", 4100000);
        zzhs.zzkb = new com.google.android.gms.drive.metadata.internal.zzb("isOpenable", 7200000);
        zzhs.zzkc = new com.google.android.gms.drive.metadata.internal.zzb("isRestricted", 4300000);
        zzhs.zzkd = new com.google.android.gms.drive.metadata.internal.zzb("isShared", 4300000);
        zzhs.zzke = new com.google.android.gms.drive.metadata.internal.zzb("isGooglePhotosFolder", 7000000);
        zzhs.zzkf = new com.google.android.gms.drive.metadata.internal.zzb("isGooglePhotosRootFolder", 7000000);
        zzhs.zzkg = new com.google.android.gms.drive.metadata.internal.zzb("isTrashable", 4400000);
        zzhs.zzkh = new com.google.android.gms.drive.metadata.internal.zzb("isViewed", 4300000);
        zzhs.zzki = new zzhx(4100000);
        zzhs.zzkj = new zzt("originalFilename", 4300000);
        zzhs.zzkk = new zzs("ownerNames", 4300000);
        zzhs.zzkl = new zzu("lastModifyingUser", 6000000);
        zzhs.zzkm = new zzu("sharingUser", 6000000);
        zzhs.zzkn = new zzo(4100000);
        zzhs.zzko = new zzhy("quotaBytesUsed", 4300000);
        zzhs.zzkp = new zzia("starred", 4100000);
        zzhs.zzkq = new zzhu("thumbnail", Collections.emptySet(), Collections.emptySet(), 4400000);
        zzhs.zzkr = new zzib("title", 4100000);
        zzhs.zzks = new zzic("trashed", 4100000);
        zzhs.zzkt = new zzt("webContentLink", 4300000);
        zzhs.zzku = new zzt("webViewLink", 4300000);
        zzhs.zzkv = new zzt("uniqueIdentifier", 5000000);
        zzhs.zzkw = new com.google.android.gms.drive.metadata.internal.zzb("writersCanShare", 6000000);
        zzhs.zzkx = new zzt("role", 6000000);
        zzhs.zzky = new zzt("md5Checksum", 7000000);
        zzhs.zzkz = new zzhz(7000000);
        zzhs.zzla = new zzt("recencyReason", 8000000);
        zzhs.zzlb = new com.google.android.gms.drive.metadata.internal.zzb("subscribed", 8000000);
    }
}

