package com.android.billingclient.api;

final class zzca {
    static final BillingResult zzA;
    static final BillingResult zzB;
    static final BillingResult zzC;
    static final BillingResult zzD;
    static final BillingResult zzE;
    static final BillingResult zzF;
    public static final int zzG;
    static final BillingResult zza;
    static final BillingResult zzb;
    static final BillingResult zzc;
    static final BillingResult zzd;
    static final BillingResult zze;
    static final BillingResult zzf;
    static final BillingResult zzg;
    static final BillingResult zzh;
    static final BillingResult zzi;
    static final BillingResult zzj;
    static final BillingResult zzk;
    static final BillingResult zzl;
    static final BillingResult zzm;
    static final BillingResult zzn;
    static final BillingResult zzo;
    static final BillingResult zzp;
    static final BillingResult zzq;
    static final BillingResult zzr;
    static final BillingResult zzs;
    static final BillingResult zzt;
    static final BillingResult zzu;
    static final BillingResult zzv;
    static final BillingResult zzw;
    static final BillingResult zzx;
    static final BillingResult zzy;
    static final BillingResult zzz;

    static {
        Builder billingResult$Builder0 = BillingResult.newBuilder();
        billingResult$Builder0.setResponseCode(3);
        billingResult$Builder0.setDebugMessage("Google Play In-app Billing API version is less than 3");
        zzca.zza = billingResult$Builder0.build();
        Builder billingResult$Builder1 = BillingResult.newBuilder();
        billingResult$Builder1.setResponseCode(3);
        billingResult$Builder1.setDebugMessage("Google Play In-app Billing API version is less than 9");
        zzca.zzb = billingResult$Builder1.build();
        Builder billingResult$Builder2 = BillingResult.newBuilder();
        billingResult$Builder2.setResponseCode(3);
        billingResult$Builder2.setDebugMessage("Billing service unavailable on device.");
        zzca.zzc = billingResult$Builder2.build();
        Builder billingResult$Builder3 = BillingResult.newBuilder();
        billingResult$Builder3.setResponseCode(5);
        billingResult$Builder3.setDebugMessage("Client is already in the process of connecting to billing service.");
        zzca.zzd = billingResult$Builder3.build();
        Builder billingResult$Builder4 = BillingResult.newBuilder();
        billingResult$Builder4.setResponseCode(5);
        billingResult$Builder4.setDebugMessage("The list of SKUs can\'t be empty.");
        zzca.zze = billingResult$Builder4.build();
        Builder billingResult$Builder5 = BillingResult.newBuilder();
        billingResult$Builder5.setResponseCode(5);
        billingResult$Builder5.setDebugMessage("SKU type can\'t be empty.");
        zzca.zzf = billingResult$Builder5.build();
        Builder billingResult$Builder6 = BillingResult.newBuilder();
        billingResult$Builder6.setResponseCode(5);
        billingResult$Builder6.setDebugMessage("Product type can\'t be empty.");
        zzca.zzg = billingResult$Builder6.build();
        Builder billingResult$Builder7 = BillingResult.newBuilder();
        billingResult$Builder7.setResponseCode(-2);
        billingResult$Builder7.setDebugMessage("Client does not support extra params.");
        zzca.zzh = billingResult$Builder7.build();
        Builder billingResult$Builder8 = BillingResult.newBuilder();
        billingResult$Builder8.setResponseCode(5);
        billingResult$Builder8.setDebugMessage("Invalid purchase token.");
        zzca.zzi = billingResult$Builder8.build();
        Builder billingResult$Builder9 = BillingResult.newBuilder();
        billingResult$Builder9.setResponseCode(6);
        billingResult$Builder9.setDebugMessage("An internal error occurred.");
        zzca.zzj = billingResult$Builder9.build();
        Builder billingResult$Builder10 = BillingResult.newBuilder();
        billingResult$Builder10.setResponseCode(5);
        billingResult$Builder10.setDebugMessage("SKU can\'t be null.");
        zzca.zzk = billingResult$Builder10.build();
        Builder billingResult$Builder11 = BillingResult.newBuilder();
        billingResult$Builder11.setResponseCode(0);
        zzca.zzl = billingResult$Builder11.build();
        Builder billingResult$Builder12 = BillingResult.newBuilder();
        billingResult$Builder12.setResponseCode(-1);
        billingResult$Builder12.setDebugMessage("Service connection is disconnected.");
        zzca.zzm = billingResult$Builder12.build();
        Builder billingResult$Builder13 = BillingResult.newBuilder();
        billingResult$Builder13.setResponseCode(2);
        billingResult$Builder13.setDebugMessage("Timeout communicating with service.");
        zzca.zzn = billingResult$Builder13.build();
        Builder billingResult$Builder14 = BillingResult.newBuilder();
        billingResult$Builder14.setResponseCode(-2);
        billingResult$Builder14.setDebugMessage("Client does not support subscriptions.");
        zzca.zzo = billingResult$Builder14.build();
        Builder billingResult$Builder15 = BillingResult.newBuilder();
        billingResult$Builder15.setResponseCode(-2);
        billingResult$Builder15.setDebugMessage("Client does not support subscriptions update.");
        zzca.zzp = billingResult$Builder15.build();
        Builder billingResult$Builder16 = BillingResult.newBuilder();
        billingResult$Builder16.setResponseCode(-2);
        billingResult$Builder16.setDebugMessage("Client does not support get purchase history.");
        zzca.zzq = billingResult$Builder16.build();
        Builder billingResult$Builder17 = BillingResult.newBuilder();
        billingResult$Builder17.setResponseCode(-2);
        billingResult$Builder17.setDebugMessage("Client does not support price change confirmation.");
        zzca.zzr = billingResult$Builder17.build();
        Builder billingResult$Builder18 = BillingResult.newBuilder();
        billingResult$Builder18.setResponseCode(-2);
        billingResult$Builder18.setDebugMessage("Play Store version installed does not support cross selling products.");
        zzca.zzs = billingResult$Builder18.build();
        Builder billingResult$Builder19 = BillingResult.newBuilder();
        billingResult$Builder19.setResponseCode(-2);
        billingResult$Builder19.setDebugMessage("Client does not support multi-item purchases.");
        zzca.zzt = billingResult$Builder19.build();
        Builder billingResult$Builder20 = BillingResult.newBuilder();
        billingResult$Builder20.setResponseCode(-2);
        billingResult$Builder20.setDebugMessage("Client does not support offer_id_token.");
        zzca.zzu = billingResult$Builder20.build();
        Builder billingResult$Builder21 = BillingResult.newBuilder();
        billingResult$Builder21.setResponseCode(-2);
        billingResult$Builder21.setDebugMessage("Client does not support ProductDetails.");
        zzca.zzv = billingResult$Builder21.build();
        Builder billingResult$Builder22 = BillingResult.newBuilder();
        billingResult$Builder22.setResponseCode(-2);
        billingResult$Builder22.setDebugMessage("Client does not support in-app messages.");
        zzca.zzw = billingResult$Builder22.build();
        Builder billingResult$Builder23 = BillingResult.newBuilder();
        billingResult$Builder23.setResponseCode(-2);
        billingResult$Builder23.setDebugMessage("Client does not support user choice billing.");
        zzca.zzx = billingResult$Builder23.build();
        Builder billingResult$Builder24 = BillingResult.newBuilder();
        billingResult$Builder24.setResponseCode(-2);
        billingResult$Builder24.setDebugMessage("Play Store version installed does not support external offer.");
        zzca.zzy = billingResult$Builder24.build();
        Builder billingResult$Builder25 = BillingResult.newBuilder();
        billingResult$Builder25.setResponseCode(5);
        billingResult$Builder25.setDebugMessage("Unknown feature");
        zzca.zzz = billingResult$Builder25.build();
        Builder billingResult$Builder26 = BillingResult.newBuilder();
        billingResult$Builder26.setResponseCode(-2);
        billingResult$Builder26.setDebugMessage("Play Store version installed does not support get billing config.");
        zzca.zzA = billingResult$Builder26.build();
        Builder billingResult$Builder27 = BillingResult.newBuilder();
        billingResult$Builder27.setResponseCode(-2);
        billingResult$Builder27.setDebugMessage("Query product details with serialized docid is not supported.");
        zzca.zzB = billingResult$Builder27.build();
        Builder billingResult$Builder28 = BillingResult.newBuilder();
        billingResult$Builder28.setResponseCode(4);
        billingResult$Builder28.setDebugMessage("Item is unavailable for purchase.");
        zzca.zzC = billingResult$Builder28.build();
        Builder billingResult$Builder29 = BillingResult.newBuilder();
        billingResult$Builder29.setResponseCode(-2);
        billingResult$Builder29.setDebugMessage("Query product details with developer specified account is not supported.");
        zzca.zzD = billingResult$Builder29.build();
        Builder billingResult$Builder30 = BillingResult.newBuilder();
        billingResult$Builder30.setResponseCode(-2);
        billingResult$Builder30.setDebugMessage("Play Store version installed does not support alternative billing only.");
        zzca.zzE = billingResult$Builder30.build();
        Builder billingResult$Builder31 = BillingResult.newBuilder();
        billingResult$Builder31.setResponseCode(5);
        billingResult$Builder31.setDebugMessage("To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        zzca.zzF = billingResult$Builder31.build();
    }

    static BillingResult zza(int v, String s) {
        Builder billingResult$Builder0 = BillingResult.newBuilder();
        billingResult$Builder0.setResponseCode(v);
        billingResult$Builder0.setDebugMessage(s);
        return billingResult$Builder0.build();
    }
}

